### ISSUE TITLE
[1.12.2] FontRenderer mixin crash

### ISSUE THREAD

**Issue by TheComputerizer** [SteveKunG/SteveKunG-Lib#14]
When trying to load up 1.3.1-dev I get [this crash](https://mclo.gs/K5JK03E#L1030) which I assume means that [this shaded method](https://github.com/SteveKunG/SteveKunG-Lib/blob/ad5ef9f4137c0f4d11791b1fd96933fd93cf4715/src/main/java/stevekung/mods/stevekunglib/mixin/ColoredFontRendererMixin.java#L26) should be marked as `remap = false`

**Comment by SteveKunG** [comment]
Oops, Recently I've change my buildscript and it upload dev artifact instead of production artifact :(.
Please redownload using this link, once curseforge is approved.
https://legacy.curseforge.com/minecraft/mc-mods/stevekungs-lib/files/5064118
