### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by Kevadroz** [SteveKunG/SteveKunG-Lib#2]
I updated the library and now the game crashes on launch. Incompatibility with another mod?
[LOG](https://paste.dimdev.org/raw/vivujodufu)
[List of mods](https://paste.dimdev.org/raw/qituxesoso)

**Comment by Kevadroz** [comment]
I don't think you can find the issue with just that if it's a mod incompatibility so here's a [crashlog](https://paste.dimdev.org/qituxesoso.mccrash) (with the list of mods) (this library and MorePlanets are outdated so I could load the game, but the issue occurs on the newer versions). I also updated the main comment with the list of mods.

**Comment by SteveKunG** [comment]
Seems work fine to me, with your mod list (tested all coremods) : https://pastebin.com/hgJfPras
Not sure what mod causing this...

**Comment by Kevadroz** [comment]
Maybe OptiFine?

**Comment by SteveKunG** [comment]
I have latest OptiFine in my test environment.

**Comment by Kevadroz** [comment]
I have E4 pre4

**Comment by Kevadroz** [comment]
The last version where it didn't crash was on 1.0.5.

**Comment by Kevadroz** [comment]
OptiFine Isn't the problem

**Comment by SteveKunG** [comment]
Or you should keep using SteveKunG's Lib 1.0.5 or remove it, it doesn't need in current version of More Planets.

**Comment by ghost** [comment]
I'm having this same problem after updating More Planets to 2.1.6 and SteveKunG's Lib to 1.1.1. Minecraft 1.12.2, Forge 2838. 

Mod list and crash log: https://pastebin.com/WtkbZjW8

I would be happy to provide more information in order to get this fixed and be able to use the latest versions of your mods in my modpack

**Comment by ghost** [comment]
And it seems that More Planets 2.1.5 is not compatible with the most recent Galacticraft release so I'll have to downgrade back to an older version of Galacticraft as well.

As I stated above, I would be happy to provide any additional details I can to resolve this so that I can use the newest versions of these mods again.

**Comment by SteveKunG** [comment]
Workaround an issue with GuiScreen, I think its load Minecraft.class early....
Please try it with this : https://www.dropbox.com/s/lvbss7rq6wx74kd/SteveKunG%27s-Lib-1.12.2-1.1.1.jar?dl=1

**Comment by ghost** [comment]
Hi, I tried loading my pack using the jar from DropBox but got the same error. :(

**Comment by SteveKunG** [comment]
Ah, this is so hard to reproduce this.
OK, I've changed priority of mixin injection. It should help maybe...
https://www.dropbox.com/s/cg32bn4z001rzyl/SteveKunG%27s-Lib-1.12.2-1.1.2.jar?dl=1

**Comment by SteveKunG** [comment]
So, does it work?

**Comment by ghost** [comment]
Sorry just got home from work and am able to test this.

Unfortunately still getting the same startup crash using the 1.1.2 build.

If it helps the pack I'm playing is the latest release (1.8.0) of the [Star Tech modpack](https://www.curseforge.com/minecraft/modpacks/star-tech). Attempting to manually update Galacticraft, More Planets and SteveKunG's lib to their latest releases causes the startup crash (maybe helpful for reproducing).

**Comment by SteveKunG** [comment]
I found it was caused by RandomPatches mod, Might be temporary remove it from your current mod pack.

**Comment by ghost** [comment]
Thanks for looking into this! Unfortunately I am still getting a startup crash even with the latest 1.1.2 release and RandomPatches. I can confirm that removing that mod allows the game to start.

Is this something that should be brought up on the RandomPatches repo as well to help come to a solution?

**Comment by Kevadroz** [comment]
If I try to reproduce the issue with just SteveKunGLib, More Planets, Galacticraft (Planets), and RandomPatches the game will load, but the issue persists in my other instance. So I believe It's an issue that consists on a conflict between more than 2 mods. Maybe OptiFine + RandomPatches?

Edit: Game seems to load fine up to Initialization with OptiFine + RandomPatches

**Comment by SteveKunG** [comment]
By the way, its also conflict with VanillaFix. Try to remove RandomPatches or VanillaFix.
@geobr1990 You don't need to report them, because it's coremod so no one support it.

**Comment by ghost** [comment]
Unfortunately VanillaFix is a bit of a must have for me due to the age of my computer and without it I get an almost unplayable framerate. RandomPatches is nice to have as well due to it fixing the connection timeout issue when connecting to servers, but I may be able to live with that if I had to.

**Comment by SteveKunG** [comment]
Fixed now.
https://www.curseforge.com/minecraft/mc-mods/stevekungs-lib/files/2757225

**Comment by ghost** [comment]
Thank you so much!
