### ISSUE TITLE
[1.12.2] Mixin Crash

### ISSUE THREAD

**Issue by Diamondman121314** [SteveKunG/SteveKunG-Lib#5]
Within the past three days, two mods that I use, Surge and VanillaFix, have both updated for 1.12.2. Both of them have updated their Mixins to 0.8. From what I can tell, now both of those mods are incompatible with this mod now.
https://gist.github.com/Diamondman121314/6002aad8c1ab8aff34e19f7eb566e42e
I know it doesn't specifically say your mod in here, but I did some testing without both of those mods first, then looked for any mods that use Mixins that I have, tested it without this mod and no crash.

**Comment by SteveKunG** [comment]
It break all mods that use Mixin 0.7 or below, I think you should use a stable version of these mods.
Also it's time to discontinued for 1.12

**Comment by Diamondman121314** [comment]
I mean, I am using a VanillaFix file marked as release on CurseForge. Anyway, that's understandable. I just renamed one of the mods with Mixin 0.8 so it appears above this mod, so that works. Thanks anyway!
