### ISSUE TITLE
Lag spikes when using enchantment table

### ISSUE THREAD

**Issue by MYSTRAVIL** [SteveKunG/SteveKunG-Lib#6]
When putting something in the enchantment table, my FPS just drops to 1. This mod puts out this in the console every second: "Unicode Font initialized"

The GL Errors are from another mod.

[latest.log](https://github.com/SteveKunG/SteveKunG-Lib/files/4425678/latest.log)

**Comment by SteveKunG** [comment]
Fixed in 2.0.2.
