### ISSUE TITLE
Vivecraft 1.12.2 Exit Code 0

### ISSUE THREAD

**Issue by roshan-c** [SteveKunG/SteveKunG-Lib#8]
Vivecraft 1.12.2 Forge 2854 crashes trying to launch only when SteveKunG-Lib is in my mods folder. Admittedly, it is an older version, however, still wanted to bring to your attention.

**Comment by SteveKunG** [comment]
Any log provide?

**Comment by roshan-c** [comment]
yeah, sorry completely forgot!
[2020-12-05-2.log](https://github.com/SteveKunG/SteveKunG-Lib/files/5659489/2020-12-05-2.log)

**Comment by Secretname2009** [comment]
Im having this issue with Vivecraft and SteveKunG-Lib aswell. Im trying to start the game using my modset that has the two mentioned mods along with More Planets and several other Mods. I will attach the log that states what happends.

Minecraft Forge Version 14.23.5.2854 with 1.12.2
SteveKunG-Lib Version: 1.1.9
More Planets Version: 2.2.0-GC281
[latest.log](https://github.com/SteveKunG/SteveKunG-Lib/files/5787701/latest.log)

**Comment by SteveKunG** [comment]
Please test with 1.1.10 https://www.dropbox.com/s/cyyxv45lb6vuk8h/SteveKunG%27s-Lib-1.12.2-1.1.10.jar?dl=0

**Comment by Secretname2009** [comment]
I tried it but it still failed however with a different error.
Here is the latest log.
[latest.log](https://github.com/SteveKunG/SteveKunG-Lib/files/5862955/latest.log)

**Comment by SteveKunG** [comment]
Most likely mixin issue.
https://www.dropbox.com/s/nz1til4bpwsbwdg/SteveKunG%27s-Lib-1.12.2-1.1.10.jar?dl=1

**Comment by Secretname2009** [comment]
Minecraft sucessfully got to main menu but i cannot test it at the moment. I will get back to this once i can.

**Comment by SteveKunG** [comment]
Please try with this version, I think its working for now.
https://www.curseforge.com/minecraft/mc-mods/stevekungs-lib/files/3230683
